breakouts:
  - { id: 'swp11', breakout: '4x', lanes: '2' }

mlag_bonds:
  - id: 'bond10'
    mlagid: 10
    members:
      - id: 'swp1'
      - id: 'swp2'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '95'
      - id: '96'
      - id: '98'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '104'
      - id: '106'
      - id: '107'
      - id: '232'
      - id: '656'
  - id: 'bond270'
    mlagid: 270
    members:
      - id: 'swp27'
      - id: 'swp28'
      - id: 'swp29'
      - id: 'swp30'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '105'
      - id: '106'
      - id: '107'
      - id: '232'
      - id: '656'

mlag_bonds_hybrid:
  - id: 'bond30'
    mlagid: 30
    members:
      - id: 'swp3'
    bridge: 'br_default'
    vlan:
      - id: '74'
    untagged: '74'
  - id: 'bond40'
    mlagid: 40
    members:
      - id: 'swp4'
    bridge: 'br_default'
    vlan:
      - id: '74'
    untagged: '74'
  - id: 'bond50'
    mlagid: 50
    members:
      - id: 'swp5'
    bridge: 'br_default'
    vlan:
      - id: '74'
    untagged: '74'
  - id: 'bond60'
    mlagid: 60
    members:
      - id: 'swp6'
    bridge: 'br_default'
    vlan:
      - id: '74'
    untagged: '74'
  - id: 'bond70'
    mlagid: 70
    members:
      - id: 'swp7'
    bridge: 'br_default'
    vlan:
      - id: '74'
    untagged: '74'
  - id: 'bond80'
    mlagid: 80
    members:
      - id: 'swp8'
    bridge: 'br_default'
    vlan:
      - id: '74'
    untagged: '74'
  - id: 'bond110'
    mlagid: 110
    members:
      - id: 'swp11s0'
    bridge: 'br_default'
    vlan:
      - id: '656'
    untagged: '656'
  - id: 'bond111'
    mlagid: 111
    members:
      - id: 'swp11s1'
    bridge: 'br_default'
    vlan:
      - id: '656'
    untagged: '656'
