breakouts:
  - { id: 'swp1', breakout: '2x', lanes: '4' }
  - { id: 'swp3', breakout: '8x', lanes: '1' }
  - { id: 'swp57', breakout: '8x', lanes: '1' }
  - { id: 'swp59', breakout: '2x', lanes: '4' }
  - { id: 'swp60', breakout: '2x', lanes: '4' }
  - { id: 'swp61', breakout: '2x', lanes: '4' }
  - { id: 'swp62', breakout: '2x', lanes: '4' }

mlag_bonds:
  - id: 'bond10'
    mlagid: 10
    members: 
      - id: 'swp1s0'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '656'
  - id: 'bond20'
    mlagid: 20
    members: 
      - id: 'swp2s0'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '105'
      - id: '106'
      - id: '107'
      - id: '656'
  - id: 'bond21'
    mlagid: 21
    members: 
      - id: 'swp2s1'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '105'
      - id: '106'
      - id: '107'
      - id: '656'
  - id: 'bond22'
    mlagid: 22
    members: 
      - id: 'swp2s2'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '105'
      - id: '106'
      - id: '107'
      - id: '656'
  - id: 'bond570'
    mlagid: 570
    members: 
      - id: 'swp57s0'
      - id: 'swp57s1'
    bridge: 'br_default'
    vlan:
      - id: '73'
      - id: '74'
      - id: '78'
      - id: '93'
      - id: '94'
      - id: '96'
      - id: '103'
      - id: '106'
      - id: '656'
  - id: 'bond610'
    mlagid: 610
    members: 
      - id: 'swp61s0'
      - id: 'swp61s1'
      - id: 'swp62s0'
      - id: 'swp62s1'
    bridge: 'br_default'
    vlan:
      - id: '50'
      - id: '51'
      - id: '52'
      - id: '54'
      - id: '55'
      - id: '60'
      - id: '70'
      - id: '71'
      - id: '72'
      - id: '73'
      - id: '74'
      - id: '75'
      - id: '76'
      - id: '77'
      - id: '78'
      - id: '79'
      - id: '83'
      - id: '84'
      - id: '86'
      - id: '87'
      - id: '88'
      - id: '89'
      - id: '90'
      - id: '91'
      - id: '92'
      - id: '93'
      - id: '94'
      - id: '99'
      - id: '100'
      - id: '101'
      - id: '102'
      - id: '103'
      - id: '105'
      - id: '106'
      - id: '107'
      - id: '232'
      - id: '656'

mlag_bonds_hybrid:
  - id: 'bond11'
    mlagid: 11
    members:
      - id: 'swp1s1'
    bridge: 'br_default'
    vlan:
      - id: '232'
    untagged: '232'
  - id: 'bond24'
    mlagid: 24
    members: 
      - id: 'swp2s4'
    bridge: 'br_default'
    vlan:
      - id: '54'
      - id: '86'
    untagged: '54'
  - id: 'bond25'
    mlagid: 25
    members: 
      - id: 'swp2s5'
    bridge: 'br_default'
    vlan:
      - id: '54'
      - id: '73'
    untagged: '54'
  - id: 'bond26'
    mlagid: 26
    members: 
      - id: 'swp2s6'
    bridge: 'br_default'
    vlan:
      - id: '54'
      - id: '86'
    untagged: '54'
