---
ansible_host: "192.168.200.11"

mgmt_addresses:
  - eth0_ip: "192.168.200.11/24"
    lo_ip: "10.10.10.2/32"

system:
  - hostname: "2010-1-B"
    timezone: "America/New_York"

vlans:
  - vlan: [id: '10', id: '20']

mlag_config:
  - { mlag_mac: "44:38:39:BE:EF:AC", mlag_backup: "10.10.10.1", members: [id: 'swp17', id: 'swp18'] }

mlag_bonds:
  - { id: 'bond1', mlagid: 1, members: [id: 'swp1'], bridge: 'br_default'}
  - { id: 'bond19', mlagid: 19, members: [id: 'swp19', id: 'swp20'], bridge: 'br_default'}
