---
ansible_host: "192.168.200.11"
hostname: "2010-1-B"
eth0_ip: "192.168.200.11/24"
lo_ip: "10.10.10.2/32"
vlan_config: 
  - { id: 'vlan10', ip: '10.1.10.11/24', vlan: '10'}
mlag_config:
  - mlag_mac: "44:38:39:BE:EF:AC"
    mlag_backup: "10.10.10.1"
    members:
      - id: 'swp17'
      - id: 'swp18'
