---
mgmt_addresses:
  - eth0_ip: "192.168.200.21/24"
    lo_ip: "10.10.10.1/32"

system:
  - hostname: "2201-1"
    timezone: "America/New_York"

vlans:
  - vlan: ['10', '20']

interfaces:
  - { id: 'swp1', bridge: 'br_default' }

bonds:
  - { id: 'bond49', members: [id: 'swp49', id: 'swp50'], bridge: 'br_default'}
