---
mgmt_addresses:
  - eth0_ip: "192.168.200.4/24"
  - lo_ip: "10.10.10.1/32"

system:
  - hostname: "4700-1-A"
  - timezone: "America/New_York"

vlans:
  - vlan: ['10', '20']

mlag_config:
  - { mlag_mac: "44:38:39:BE:EF:AA", mlag_backup: "10.10.10.2", members: [id: 'swp31', id: 'swp32'] }

mlag_bonds:
  - { id: 'bond1', mlagid: 1, members: [id: 'swp1'], bridge: 'br_default'}
  - { id: 'bond27', mlagid: 27, members: [id: 'swp27', id: 'swp28', id: 'swp29', id: 'swp30'], bridge: 'br_default'}
