---
ansible_host: "192.168.200.2"
hostname: "5600-1-A"
eth0_ip: "192.168.200.2/24"
lo_ip: "10.10.10.1/32"
vlan_config: 
  - { id: 'vlan10', ip: '10.1.10.2/24', vlan: '10'}
mlag_config:
  - mlag_mac: "44:38:39:BE:EF:AB"
    mlag_backup: "10.10.10.2"
    members:
      - id: 'swp63'
      - id: 'swp64'
