---
ansible_host: "192.168.200.3"

mgmt_addresses:
  - eth0_ip: "192.168.200.3/24"
    lo_ip: "10.10.10.2/32"

system:
  - hostname: "spine-800g-02"
    timezone: "America/New_York"

#vlan_interfaces:
#  - { id: 'vlan10', ip: '10.1.10.3/24', vlan: '10'}
#  - { id: 'vlan20', ip: '10.1.20.3/24', vlan: '20'}

mlag_config:
  - { mlag_mac: "44:38:39:BE:EF:AB", mlag_backup: "10.10.10.1", members: [id: 'swp63', id: 'swp64'] }
