---
- name: Playbook to update bridge vlan settings
  hosts: switches
  connection: ansible.netcommon.httpapi
  gather_facts: false
  vars:
    ansible_network_os: nvidia.nvue.httpapi
    ansible_httpapi_port: 8765
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false

  tasks:
    - name: Create new revision
      nvidia.nvue.config:
        state: new
      register: revision

    - name: Set bridge
      nvidia.nvue.bridge:
        state: merged
        revid: '{{ revision.revid }}'
        data:
          - id: 'br_default'
            type: 'vlan-aware'
            vlan:
              - id: '{{ item.vlan }}'
                vni:
                  - id: '{{ item.vlan }}'
      with_items: '{{ vlans }}'
      register: bridge

    - name: Apply new revision
      nvidia.nvue.config:
        state: apply
        revid: '{{ revision.revid }}'
        force: true
        wait: 10
      register: revision
