---
- name: Test playbook to update interface settings
  hosts: mlag
  connection: ansible.netcommon.httpapi
  gather_facts: false
  vars:
    ansible_network_os: nvidia.nvue.httpapi
    ansible_httpapi_port: 8765
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false

  tasks:
    - name: Create new revision
      nvidia.nvue.config:
        state: new
      register: revision

    - name: Set MLAG interfaces
      nvidia.nvue.interface:
        state: merged
        revid: '{{ revision.revid }}'
        data:
          - id: 'peerlink'
            bond:
              member: '{{ item.members }}'
            bridge:
              domain:
                - id: 'br_default'
            type: 'peerlink'
      with_items: "{{ mlag_config }}"
      register: interface

    - name: Set mlag
      nvidia.nvue.mlag:
        state: merged
        revid: '{{ revision.revid }}'
        data:
          enable: 'on'
          init_delay: 100
          mac_address: '{{ item.mlag_mac }}'
          backup:
            - id: '{{ item.mlag_backup }}'
          peer_ip: 'linklocal'
          priority: 1000
      with_items: "{{ mlag_config }}"
      register: mlag

    - name: Apply new revision
      nvidia.nvue.config:
        state: apply
        revid: '{{ revision.revid }}'
        force: true
        wait: 10
      register: revision
