---

- name: Test playbook to setup system config on leaf switches
  hosts: switches
  connection: ansible.netcommon.httpapi
  gather_facts: false
  vars:
    ansible_network_os: nvidia.nvue.httpapi
    ansible_httpapi_port: 8765
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false

  tasks:
    - name: Create new revision
      nvidia.nvue.config:
        state: new
      register: revision

    - name: Set system settings
      nvidia.nvue.system:
        state: merged
        revid: '{{ revision.revid }}'
        data:
          hostname: '{{ item.hostname }}'
          timezone: '{{ item.timezone }}'
      with_items: '{{ system }}' 
      register: system

    - name: Apply new revision
      nvidia.nvue.config:
        state: apply
        revid: '{{ revision.revid }}'
        force: true
        wait: 10
      register: revision 
